### ISSUE TITLE
Keepalive scheduled while pingreq already active.

### ISSUE THREAD

**Issue by kcallin** [kcallin/haka-mqtt#16]
2018-12-12 20:54:11 INFO mqtt Launching message MqttPingreq().
2018-12-12 20:54:11 DEBUG mqtt send 2 bytes 0xc000.
2018-12-12 20:54:11 DEBUG mqtt recv 2 bytes 0xd000
2018-12-12 20:54:11 INFO mqtt Received MqttPingresp().
2018-12-12 21:04:11 INFO mqtt Launching message MqttPingreq().
2018-12-12 21:04:11 DEBUG mqtt send 2 bytes 0xc000.
2018-12-12 21:09:11 CRITICAL root An unexpected exception forced program termination.
Traceback (most recent call last):
  File "/root/gwos/target/buildroot-2016.11.2/output/target/usr/lib/python2.7/site-packages/opi_gw_cnv2/gwdaemon.py", line 475, in main
  File "/root/gwos/target/buildroot-2016.11.2/output/target/usr/lib/python2.7/site-packages/opi_gw_cnv2/gwdaemon.py", line 179, in main_loop
  File "/root/gwos/target/buildroot-2016.11.2/output/target/usr/lib/python2.7/site-packages/opi_std/scheduler.py", line 99, in poll
  File "/root/gwos/target/buildroot-2016.11.2/output/target/usr/lib/python2.7/site-packages/haka_mqtt/reactor.py", line 2097, in __recv_idle_abort_timeout
AssertionError

**Comment by kcallin** [comment]
Bug is triggered when a pingreq is in-the-air and some operation triggers a write.  This schedules a new pingreq to be scheduled.  There is no danger of the pingreq actually being launched, but if a recv_idle_abort_timeout occurs while in this condition an assertion fails.

This is a crashing bug.
