### ISSUE TITLE
Assertion failure in __recv_idle_abort_timeout handler.

### ISSUE THREAD

**Issue by kcallin** [kcallin/haka-mqtt#28]
```
 Traceback (most recent call last):
File "/root/gwos/target/buildroot-2016.11.2/output/target/usr/lib/python2.7/site-packages/opi_gw_cnv2/gwdaemon.py", line 475, in main
File "/root/gwos/target/buildroot-2016.11.2/output/target/usr/lib/python2.7/site-packages/opi_gw_cnv2/gwdaemon.py", line 179, in main_loop
File "/root/gwos/target/buildroot-2016.11.2/output/target/usr/lib/python2.7/site-packages/opi_std/scheduler.py", line 99, in poll
File "/root/gwos/target/buildroot-2016.11.2/output/target/usr/lib/python2.7/site-packages/haka_mqtt/reactor.py", line 2102, in __recv_idle_abort_timeout
AssertionError
```

**Comment by kcallin** [comment]
Assertion error results when an outgoing message is launched within recv_abort_period of a timeout.  It is the result of a conflict between the timing of keepalive messages and the idle recv timeout.
